### ISSUE TITLE
How can i write scope without scopes option in changelog.config.js?

### ISSUE THREAD

**Issue by jetaimefrc** [streamich/git-cz#104]
If Scopes is null => Your code will ignore the writing scope 😢.
Besides, I don't want to fix the scopes, nobody does that!
How can I do that?

**Comment by mamoruuu** [comment]
It doesn't seem to support typing he scopes. But you can try to [modify](https://github.com/mokkabonna/inquirer-autocomplete-prompt) the scopes question though.
