### ISSUE TITLE
3.3.0 does not contain latest disableEmoji fix

### ISSUE THREAD

**Issue by StephanBijzitter** [streamich/git-cz#107]
Hello there!

I found a bug with disableEmoji, but it turns out the fix is already in master and is tagged with the 3.3.0 release: https://github.com/streamich/git-cz/commit/62915be714fc9628c4dba06e37c59f4212e5a532

However... I have installed 3.3.0 and in my `node_modules/git-cz/dist/cz.js` I find this: `const closedIssueEmoji = config.disableEmoji ? config.closedIssuePrefix : '';`.

So it turns out that this fix has not actually been released yet. Don't know where that went wrong, but it does mean that I still experience the bug 😅

**Comment by rodrigograca31** [comment]
@StephanBijzitter has this been solved? 🤔

**Comment by streamich** [comment]
Please try the latest version

```
npm i -g git-cz@4.5
```

**Comment by StephanBijzitter** [comment]
Yup, solved indeed. :-)
