### ISSUE TITLE
Broken icon/emoji

### ISSUE THREAD

**Issue by privateOmega** [streamich/git-cz#115]
Icons/Emojis are broken in 3.3.0 release for Windows

![image](https://user-images.githubusercontent.com/10467133/71808159-0aef4480-3093-11ea-9360-cd7351520eeb.png)

**Comment by mamoruuu** [comment]
It's not git-cz's problem. The terminal emulator itself cannot load the emoji font.
If you're using the vscode's terminal try to add emoji font family name in `Terminal` > `Integrated` > `Font family` so it looks like `'Droid Sans Mono', 'monospace', *put_emoji_font_name_here*, monospace, 'Droid Sans Fallback'`.

**Comment by privateOmega** [comment]
Closing the issue since it isn't a bug from git-cz side.
