### ISSUE TITLE
Error: Could not find Git root folder

### ISSUE THREAD

**Issue by alexeychikk** [streamich/git-cz#12]
Usages of `/dev/null` make this package unusable on Windows. Please, could you look at these files
https://github.com/streamich/git-cz/blob/c0e4ca83f8ff24146bfaf4e6134c8e35b7def15c/lib/util/getGitRootDir.js#L4
 https://github.com/streamich/git-cz/blob/c0e4ca83f8ff24146bfaf4e6134c8e35b7def15c/lib/util/lerna.js#L31

**Comment by streamich** [comment]
Any ideas for the best solution? Check for Windows, if true, don't use `2>/dev/null`?
