### ISSUE TITLE
Non-interactive CLI

### ISSUE THREAD

**Issue by streamich** [streamich/git-cz#122]
Add ability to create `git-cz`-like commits in non-interactive mode where all parameters are provided through CLI arguments and no UI is displayed. For example:

```
git-cz --non-interactive --message="First commit" --type=feat
```

All arguments could be optional, but could also be overwritten through CLI arguments:

- [ ] `--message`
- [ ] `--type`
- [ ] `--scope`
- [ ] `--description`
- [ ] etc.

**Comment by theashraf** [comment]
I'd like to help with this one

**Comment by streamich** [comment]
@theashraf that would be great!
