### ISSUE TITLE
disable emoji on CLI

### ISSUE THREAD

**Issue by PauloGoncalvesBH** [streamich/git-cz#132]
Add option on CLI to disable emoji, like:
`git-cz --disable-emoji`

Many times I only want commit without emoji, and to do that I need to create the file `changelog.config.js`.

**Comment by streamich** [comment]
Good idea

**Comment by theashraf** [comment]
can I work on this?

**Comment by streamich** [comment]
@theashraf of course

**Comment by PauloGoncalvesBH** [comment]
I think `git-cz -no-emoji` or `git-cz --emoji false` is better.

**Comment by theashraf** [comment]
how about `--emojiless` ?

**Comment by PauloGoncalvesBH** [comment]
> how about `--emojiless` ?

Isn't less emoji, but none emoji :\

**Comment by rodrigograca31** [comment]
I think there should be a way to use a global `changelog.config.js` instead, where we could specify stuff for all our projects.

**Comment by kimhjona** [comment]
Can the PR above be merged? Definitely needing this feature right now

**Comment by PauloGoncalvesBH** [comment]
@streamich
