### ISSUE TITLE
Unable to use npx git-cz

### ISSUE THREAD

**Issue by ArrayKnight** [streamich/git-cz#143]
It's really confusing about which of the repos actually owns `npx git-cz`, but here's a link to the already open issue: https://github.com/commitizen/cz-cli/issues/701

I'm unable to commit anything with `npx git-cz` right now.

@streamich This is a major breaking issue! Please help

**Comment by umutcanbolat** [comment]
I am getting the same error. However, running the npx command with the previous version number works for now. Try `npx git-cz@4.2.0` @ArrayKnight 

![image](https://user-images.githubusercontent.com/10065235/73615538-c0250600-4619-11ea-991f-c0900479c4bd.png)

**Comment by ArrayKnight** [comment]
Thank you @umutcanbolat that will get us by for now

**Comment by jimthedev** [comment]
Yeah I’ve attempted a proposal [here](https://github.com/streamich/git-cz/issues/61)  to help with the npm naming confusion but alas I don’t have a ton I can do without breaking the ecosystem. If anyone else has other ideas I’m open to hearing them.

**Comment by rodrigograca31** [comment]
@ArrayKnight and @umutcanbolat 
Can you guys confirm that `npx git-cz` is working again?

Also, I would personally sugest you avoid using npx because of typosquatting.
(Any typo can result in downloading a malicious package published using a similar name)

`npm install -g git-cz`

**Comment by ArrayKnight** [comment]
Yup, it's working

**Comment by rodrigograca31** [comment]
Great! One less issue! :wink: :muscle:
