### ISSUE TITLE
Release 1.8.1 just broke commiting

### ISSUE THREAD

**Issue by SheepFromHeaven** [streamich/git-cz#15]
When running npx git-cz it is failing right now with:

`fatal     Error: Could not find Git root folder.`

Since 15min which is the release time :(

Edit: I'm on Mac

**Comment by GeorgeZhangZHY** [comment]
Me too, 1.8.0 works fine. Now I have to give up using `npx git-cz`, but manually `npm i -g git-cz@1.8.0` and run `git-cz`

**Comment by streamich** [comment]
Thanks for reporting this! Version `1.8.2` works now.

**Comment by SheepFromHeaven** [comment]
@GeorgeZhangZHY you can also do `npx git-cz@1.8.0` for the next time ;)
