### ISSUE TITLE
Can't find local pkgs when run from global

### ISSUE THREAD

**Issue by snebjorn** [streamich/git-cz#156]
Using "Install locally with Commitizen"
```
npm i -g commitizen
npm i -D git-cz
npm i -D commitiquette
```
```
  "config": {
    "commitizen": {
      "path": "commitiquette"
    }
  },
```

When running

```
> git cz
Could not resolve commitiquette. Cannot find module 'commitiquette'

> git-cz
Could not resolve commitiquette. Cannot find module 'commitiquette'
```

This works
```
  "scripts": {
    "commit": "git-cz"
  },
```
`> npm run commit`

**Comment by StanLindsey** [comment]
This is standard NPM behaviour, the dependency isn't injected into your CLI profile but is available for NPM to find. 

If you wish to use `git-cz` directly you have a few options:
a. install globally: `npm i -g git-cz`
b. create a script, as you have done.
c. run the copy of `git-cz` that you installed directly: > `node node_modules/git-cz/dist/cli.js`

I'd suggest installing it globally personally.
