### ISSUE TITLE
Where did (scope) go?

### ISSUE THREAD

**Issue by rodrigograca31** [streamich/git-cz#164]
Why doesnt `git cz` ask for the scope?

![image](https://user-images.githubusercontent.com/1134310/78597924-3e826c00-7846-11ea-9945-f040f24b1851.png)

Looking at this repo it self theres almost no `(scope)`

**Comment by gharel** [comment]
I try another version (3.2.1) but scope still missing in interactive mode, maybe we miss some configuration in changelog.config.js ?

**Comment by gharel** [comment]
After research, you have to put, some scope in changelog.config.js
`"scopes": ["example"]` see https://github.com/streamich/git-cz#custom-config.
But you cannot enter scope, like body by enter text directly. If you want this, like me, use commitizen instead.

Hope this help.

**Comment by rodrigograca31** [comment]
Yeah, seems specifying the scopes works. Is that the intended behavior? Or is this a bug? 🐛

Do we really have to specify all our scopes first for each project? 
Can't we just type it directly? Does commitizen allow direct typing?

**Comment by gharel** [comment]
Yes it is the intended behavior if you look the source code in questions folder.
So I guess you have to specify all scopes at first time for each project.
Maybe, someone could make a PR to upgrade behavior and do both.
Il you want to type directly, commitizen works like that, so I choose to use it instead of git-cz

**Comment by StanLindsey** [comment]
@rodrigograca31 - I thought this made sense. I've pushed a new version of [@stanlindsey/git-cz](https://www.npmjs.com/package/@stanlindsey/git-cz) that allows you to manually write scopes during a commit. Just set `enableWritingScopes: true` in your config.

**Comment by rodrigograca31** [comment]
dope! 
I got my team using `git cz` but doesnt have this feature or the recursive search for config file... :sob: 

Seems we should eventually all start using your branch from now on......... :)

**Comment by StanLindsey** [comment]
We'll see.

I use it heavily and so I hope be continue to maintain it. It _shouldn't_ need a huge amount of maintenance anyway. You can always move back if things change.

**Comment by rodrigograca31** [comment]
:+1: 

@StanLindsey would you allow me to re-do the other PR? and send it again? 
(because of your last commit....)
to see if we can get that feature in the main repo.

**Comment by StanLindsey** [comment]
Yeah sure, open a PR in my repo and i'll check it all out.

**Comment by Flo-Slv** [comment]
Hi,

is this option available now ? ```enableWritingScopes: true```

**Comment by LentoYe** [comment]
I guess you can use this config in the version of [@stanlindsey/git-cz](https://www.npmjs.com/package/@stanlindsey/git-cz), but can't in this repo.

**Comment by ooing** [comment]
> I guess you can use this config in the version of [@stanlindsey/git-cz](https://www.npmjs.com/package/@stanlindsey/git-cz), but can't in this repo.

hello,  How to solve it ,thank
