### ISSUE TITLE
Global config file?

### ISSUE THREAD

**Issue by rodrigograca31** [streamich/git-cz#165]
Hi

I'd like to be able to make the config file global to all my projects instead of the current one as I expressed here: https://github.com/streamich/git-cz/issues/161#issuecomment-609996826

Because I'm following this "standard" https://gitmoji.carloscuesta.me/ and some of the emojis are not the same, for example ✨ is for features and I agree more with that standard than with the 🎸, same goes for other emojis you guys chose.

and I dont want to have to create a config file for each of my projects....

Thanks

**Comment by StanLindsey** [comment]
I currently have a PR open, #157 to support this.

**Comment by rodrigograca31** [comment]
@StanLindsey thats awesome! Looks like it keeps going up, thats good! It will eventually reach the user `home` directory where I wanted to have a global config.

Great! I will comment the close thing there and when that PR is accepted it will close this issue!

**Comment by StanLindsey** [comment]
@streamich - it looks like you merged a bunch of changes from my fork. Which means this issue can be closed. 

Did you also want to expand your list of collaborators, I'd be happy to help.

**Comment by streamich** [comment]
@StanLindsey thanks, closing.

> [..] I'd be happy to help.

That would be great, I've sent you an invite.

**Comment by rodrigograca31** [comment]
@streamich thanks for merging that commit! (I was using his fork)

I would also ask if I could help but I'm not sure how much code I will actually contribute... I can always contribute in general thought (issues, PR code reviews, etc)
[I already contribute to a few projects](https://www.npmjs.com/~rodrigograca31)


On another note: I hope @StanLindsey also adds other changes he did on his fork, like: 
`add ability to support writing new scopes during commit`
