### ISSUE TITLE
Check for staged files first

### ISSUE THREAD

**Issue by rodrigograca31** [streamich/git-cz#177]
Check that there is staged content before proceeding with anything.

Otherwise we fill everything and then it tells us that there's no staged changes. :sob:
`nothing added to commit.....`

[Moving this issue from a fork to here.](https://github.com/StanLindsey/git-cz/issues/1)

Anyone has any idea how to go about doing this?

**Comment by rodrigograca31** [comment]
Started working on this today and made some progress but not finished

**Comment by rodrigograca31** [comment]
Hahaha yesterday I wanted to add this task to the kanban board but I was a bit afraid and didnt.... 😅

I got this code (WIP) but it works the opposite of what is supposed to:
```javascript
const {execSync} = require('child_process');
const code = null;
try {
  code = execSync('git diff --staged --quiet --exit-code')
    .toString()
    .trim();
} catch (error) {
  throw new Error('no files staged');
}
```
meaning: it exits with a non 0 code (error) when it has files staged, we want the opposite.

Any tips!?

**Comment by syeutyu** [comment]
Hello :)
I enjoy using git-cz.

I'm wondering that why you use --exit-code flag?
I saw this information `Disable all output of the program. Implies --exit-code.`

It is not the same result of output?

document link is here: https://git-scm.com/docs/git-diff

**Comment by rodrigograca31** [comment]
yeah Im pretty sure we would have the same output without `--exit-code` but was just to be sure we were getting the [exit code](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---exit-code)....

**Comment by syeutyu** [comment]
oh, I agree with your opinion. It is more intuitive
I just wanna know there is some specific reason.
Thanks!
