### ISSUE TITLE
Unable to use npx git-cz | git-cz

### ISSUE THREAD

**Issue by varora1406** [streamich/git-cz#179]
This issue is with global version installed of git-cz.
version installed - 4.6.0
`npx git-cz` && `git-cz` giving same error of 

`'!' is not recognized as an internal or external command,
operable program or batch file.
×  fatal     Error: No files staged.`

I am running command in right folder, and it has files staged as well, which I double check and get
```
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
  ${complete_file_path}
```

**Comment by zkl2333** [comment]
https://github.com/streamich/git-cz/pull/178#issuecomment-633798588

**Comment by streamich** [comment]
https://github.com/streamich/git-cz/pull/180#issuecomment-633911600
