### ISSUE TITLE
×  fatal     Error: No files staged.

### ISSUE THREAD

**Issue by 646826** [streamich/git-cz#182]
'!' is not recognized as an internal or external command,
operable program or batch file.
×  fatal     Error: No files staged.
![image](https://user-images.githubusercontent.com/1565611/82988970-cf580700-9fae-11ea-844c-d63871ae04d9.png)

**Comment by rodrigograca31** [comment]
Please update to the latest:
`npm i -g git-cz`

there was one bug when trying to introduce a new feature and it has been reverted.
Sorry for the inconvenience.

**Comment by 646826** [comment]
I still get error
![image](https://user-images.githubusercontent.com/1565611/83001107-f3016880-a013-11ea-8934-91778dacd975.png)
![image](https://user-images.githubusercontent.com/1565611/83001138-fe549400-a013-11ea-9a01-2d6ed0b1c2b3.png)

**Comment by streamich** [comment]
This should work now:

```
npm i -g git-cz@4.6.1
```
