### ISSUE TITLE
new project just missing body and footer

### ISSUE THREAD

**Issue by xxholly32** [streamich/git-cz#197]
i was run `npx git-cz` in new project and add [first commit](https://github.com/xxholly32/git-cz-test/commit/aa9a5977176a14108032d65758eb84aacceeb779) . it was missing body and footer. did i miss sth?

![image](https://user-images.githubusercontent.com/6063358/90307866-1f3ece00-df0d-11ea-9ac4-1e63ad8f7451.png)

**Comment by ArrayKnight** [comment]
This is the same issue as https://github.com/streamich/git-cz/issues/188

Everything after the title is missing!

**Comment by xxholly32** [comment]
ty @ArrayKnight
