### ISSUE TITLE
Are we dependent on a dead project?

### ISSUE THREAD

**Issue by rodrigograca31** [streamich/git-cz#205]
Hi @streamich 

I'm not that familiar with ESLint and much less with the configurations, but this project is dependent on a project that is causing issues and it might never be updated/fixed: [eslint-config-mailonline](https://github.com/MailOnline/eslint-config-mailonline)

According to GitHub, we are their main dependant: https://github.com/MailOnline/eslint-config-mailonline/network/dependents

This project is holding quite a few dependencies from being updated:
https://github.com/MailOnline/eslint-config-mailonline/network/dependencies

Namely: eslint, babel-eslint, semantic-release, etc which causes our build to break when trying to update eslint: https://github.com/streamich/git-cz/pull/171

I've [open an issue there](https://github.com/MailOnline/eslint-config-mailonline/issues/40) but something tells me no one will fix it because [even though a commit was recently added the project hasn't been modified since 2017](https://github.com/MailOnline/eslint-config-mailonline/commits/master)

**With all this said, what can we do? Do we need that dependency? Can we substitute it with a better/updated one? What would the alternatives be?** 🤔

Like I said I don't know enough about ESLint to know what can be done here...
I'm just trying to help and move this project forward by keeping everything well oiled and moving :smile: 

Regards

**Comment by streamich** [comment]
@rodrigograca31 I guess we can copy the [ESLint config directly into `git-cz`](https://github.com/MailOnline/eslint-config-mailonline/blob/master/configurations/base.json).

Why do you think that project is dead?

**Comment by rodrigograca31** [comment]
Is that it? just one file? 🤔 And why override so many configs? Cant we do it in a simpler way? 🤔 Is there a similar set of configs we can change to?
Note: Like I said I don't know much about ESLint... I usually just see people using the airbnb one and be done. They keep it very updated.....

Answering your question: because they have PRs from 2017, 2018, 2019, 2020 that no one ever merged and their code [wasn't updated since 2017 except for a recent small fix...](https://github.com/MailOnline/eslint-config-mailonline/commits/master)

I want to move this project forward and [accept this PR](https://github.com/streamich/git-cz/pull/171) as well as others but I tracked down the failed tests to that plugin we depend on.
