### ISSUE TITLE
Config: Change issues footer message + footer length

### ISSUE THREAD

**Issue by damusix** [streamich/git-cz#215]
Referencing https://github.com/streamich/git-cz/pull/20

https://github.com/streamich/git-cz/pull/20#issuecomment-724834903
> @streamich is it possible to add a config option to change it back to `issues: `? Our team sometimes will cross reference issues in a commit across projects and we don't want to close those particular issues. 

In Gitlab, you can also reference across projects using `org/repo#22`. If you prefix with `(fixes|closes):`, it will close the issues on another project.

~~Also, the footer length limit makes it difficult to reference multiple external repo tickets `infrastructure#22` `infrastructure#23` `infrastructure#24`  `api#12`~~

It would be ideal if ~~both~~ footer text ~~and length~~ could be configurable. If this is something where the PR can be accepted quickly, I can do it this week. Need this feature ASAP.

**Comment by rodrigograca31** [comment]
hi @damusix 

Can you elaborate further on the 2 different issues? Maybe create separate issues here on GitHub?

I didn't find a footer length limit but I'm probably missing something.

**Comment by damusix** [comment]
@rodrigograca31 ok just tested the footer thing, I think I got it mixed up with the other `git-cz` module, so my bad about that.

As far as what this issue is about, it is the ability to configure the message that prefixes issues references. https://docs.gitlab.com/ee/user/project/issues/managing_issues.html#default-closing-pattern

If a commit needs to reference an issue without closing it, it is currently not possible given that the commit message is always `closes: `. The request is to optionally change this to another prefix, such as `references: `
