### ISSUE TITLE
Empty scope config break husky's commitlint commit-msg hook

### ISSUE THREAD

**Issue by anchnk** [streamich/git-cz#7]
> Note: I just gave a quick look at the source so I might make wrong assumptions. 

It seems that, by default,  `git-cz` does not give the option to enter the commit's scope.

I don't know if it's intentional. I could understand it so that it must be configured before, allowing to have a finite set of scopes in which the user can choose (and avoid the infinite growing scope list problem). 

However I am facing a use case where this is blocking (sort of) something I am trying to do. 

I am creating a **project template that can be used to bootstrap projects quickly in our company with some sort of sane defaults**. 

I included the `cz-conventional-changelog` adapter as well as husky and `commitlint` with the `config-conventinal` config for `commitlint`. If i try to commit something, husky does not validate any commit as the scope is empty (the question is not asked). 

Do you think that would make sense to configure it, so that the question can be asked and the user create a new scope if the list is empty ? That would make sense for that use case even though i would understand that thinking about scopes beforehand would be wiser.

Also, is there an option to disable emoji ? (I will look deeper in the codebase for this one)

**Comment by streamich** [comment]
Scope is omited by default on purpose, you can add available scopes in config.

You can disable emojis in the config as well.

**Comment by anchnk** [comment]
If that's by design, it works for me!

Thank you for the reply, closing this issue as no further actions are needed
