### ISSUE TITLE
Disable emoji in config

### ISSUE THREAD

**Issue by snaerth** [streamich/git-cz#8]
I love you package and my team wants to use it. But some are not happy with the emoji. Could you provide an option in the changelog.config.js that maybe disables emojis instead of showing a question mark

**Comment by snaerth** [comment]
@streamich

**Comment by streamich** [comment]
Hi, there is an option to specify specify a custom emoji. So if you set it to, say empty string `''`, it makes it a question mark?

**Comment by snaerth** [comment]
Yes if emoji is empty then it will default to question mark

**Comment by streamich** [comment]
OK, here is the question mark:

https://github.com/streamich/git-cz/blob/master/lib/questions/type.js#L4

**Comment by snaerth** [comment]
You are misunderstanding me. I would like there to be no question mark if emoji is empty. Just an empty string

**Comment by streamich** [comment]
I think I understood you :), I'm just showing you where to remove the question mark.

**Comment by snaerth** [comment]
@streamich do you want me to a PR for this?

**Comment by streamich** [comment]
Yes, please

**Comment by snaerth** [comment]
@streamich 
https://github.com/streamich/git-cz/pull/9

**Comment by snaerth** [comment]
@streamich thx for the merge. Could you as well update the package on npm for us to start using it?

**Comment by streamich** [comment]
@snaerth Thanks, your change should be now available in version `1.8.0`.

**Comment by snaerth** [comment]
Great thank you
